services:
  - type: web
    name: dashmetrics-ai
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false